# SPDX-License-Identifier: GPL-3.0-only
# Keep Rust dependencies and GitHub Actions current; security updates arrive
# as PRs automatically. (Also enable "Dependabot alerts" in the repo's
# Settings → Security for advisory notifications.)
version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
